CREATE TABLE `SC_COUNTER` (
`SC_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
`SC_REFERENCE` TEXT NOT NULL,
`SC_NAME` TEXT NOT NULL, 
`SC_COUNTER` INT NOT NULL, 
`SC_SINCE` INT(10) NOT NULL
); 
CREATE TABLE `SC_LOG` (
`SC_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
`SC_TIMESTAMP` INT(10) NOT NULL, 
`SC_IP` CHAR(15) NOT NULL, 
`SC_HOST` CHAR(100) NOT NULL, 
`SC_BROWSER` CHAR(100) NOT NULL, 
`SC_OS` CHAR(100) NOT NULL, 
`SC_LANGUAGE` CHAR(5) NOT NULL, 
`SC_REFFERER` CHAR(100) NOT NULL, 
`SC_PAGE` CHAR(100) NOT NULL
);
CREATE TABLE `SC_REFERENCE` (
`SC_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
`SC_CODE` TEXT NOT NULL,
`SC_NAME` TEXT NOT NULL
);
CREATE TABLE `SC_BLOCKIPS` (
`SC_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
`SC_IP` TEXT NOT NULL
);

INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('Unknown', 'Unknown');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('nl', 'Netherlands');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('en-gb', 'United Kingdom');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('uk', 'United Kingdom');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('en-us', 'United States');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('el', 'Estland');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('sv', 'Sweden');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('ru', 'Russia');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('de', 'Germany');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('en', 'United Kingdom');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('ko', 'Kosovo');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('es-ar', 'Argentina');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('en-ca', 'Canada');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('fr', 'France');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('nl-be', 'Belgium');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('es-mx', 'Mexico');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('es', 'Spain');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('no', 'Norway');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('it', 'Italy');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('fi', 'Finland');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('en-au', 'Australia');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('fr-be', 'Belgium');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('de-at', 'Austria');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('at', 'Austria');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('be', 'Belgium');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('pt', 'Puerto Rico');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('ch', 'Switzerland');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('ve', 'Venezuela');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('da', 'Denmark');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('en-nz', 'New zealand');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('nz', 'New zealand');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('fr-ca', 'Canada');  
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('ca', 'Canada');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('br', 'Brazil');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('pt-br', 'Brazil');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('zh-hk', 'Suriname');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('hk', 'Hongkong');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('th', 'Thailand');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('es-cl', 'Chile');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('cl', 'Chile');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('ja', 'Java');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('en-za', 'South Africa');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('za', 'South Africa');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('zh-tw', 'Taiwan');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('tw', 'Taiwan');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('fr-ch', 'Switserland');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('tr', 'Turkey');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('zh-cn', 'China');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('cn', 'China');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('bg', 'Bulgaria');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('ro', 'Romania');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('hu', 'Hungary');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('cs', 'Czechoslovakia (former)');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('eg', 'Egypt');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('ar-eg', 'Egypt');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('de-de', 'Germany');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('ar-sa', 'Saudi Arabia');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('sa', 'Saudi Arabia');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('id', 'Indonesia');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('lv', 'Latvia');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('is', 'Iceland');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('hr', 'Croatia (Hrvatska)');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('es-es', 'Spain');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('fd-fd', 'France');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('de-ch', 'Czechoslovakia (former)');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('sl', 'Sierra Leone');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('bo', 'Bolivia');
INSERT INTO `SC_REFERENCE` (`SC_CODE`, `SC_NAME`) VALUES ('es-bo', 'Bolivia');


