<br><br>
</td>

<!-- Right Table portion------------------------------------------------->
<td width=32 valign=top background="/layout/contentRightbg.jpg">
<img src="/layout/content3.jpg"><br>
</td>
</tr>
<!-- Footer Portion------------------------------------------------->
<tr><td colspan=3 width=604 height=53 background="/layout/content4.jpg" valign=top>
<center><font size=2 face="arial">
<a href="/freeImages/">Free Images</a> | 
<a href="/creations/">Creations</a> | 
<a href="/webDesign/">Web Design</a> | 
<a href="/portfolio/">Portfolio</a> | 
<a href="/tipsTricks/">Tips & Tricks</a> | 
<a href="/downloads">Downloads</a> | 
<a href="/webLinks/">Web Links</a><br>
</td>


</tr></table>

<center>
&copy; 1999 - 
<script language="javascript">document.write((new Date()).getFullYear());</script> 
<a href="http://ninjahacking.com">Phil Crosby</a><br>





<!-- Preloading Script---------------------------------------------------->
<script language="javascript">

<!--  PreLoad MouseOver Images for Compatible Browsers

browser_name = navigator.appName;

browser_version = parseFloat(navigator.appVersion); 
if (browser_name == "Netscape" && browser_version >= 3.0) { roll = 'true';}
else if (browser_name == "Microsoft Internet Explorer" && browser_version >= 4.0) { roll = 'true'; }
else { roll = 'false'; }if (roll == 'true') { var imglist = new Array(
"/layout/home2.jpg",
"/layout/contact2.jpg",
"/layout/guestbook2.jpg",
"/layout/freeImages2.jpg",
"/layout/creations2.jpg",
"/layout/webDesign2.jpg",
"/layout/portfolio2.jpg",
"/layout/tipsTricks2.jpg",
"/layout/downloads2.jpg",
"/layout/webLinks2.jpg",
"/layout/contact2.jpg");

var imgs = new Array();var count;if (document.images) for (count=0; count<imglist.length; count++)  {imgs[count]=new Image(); imgs[count].src=imglist[count];}}

// -->

</script>
